# Generated by Django 5.1 on 2025-04-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
